on:
  push:
    branches:
      - main
    paths:
      - src/Dockerfile.cuda
      - scripts/**
      - utils/**
      - .github/workflows/build-cuda.yml
      - .github/workflows/reusable-build.yml
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    permissions:
      contents: read
      packages: write
    secrets: inherit
    with:
      dockerfile: Dockerfile.cuda
      image: python-image
      tag: ubuntu-24.04-cuda
