on:
  push:
    branches:
      - main
    paths:
      - src/Dockerfile.cuda
      - scripts/**
      - utils/**
      - .github/workflows/cuda-job.yml
      - .github/workflows/reusable-job.yml
  workflow_dispatch:

jobs:
  create-job:
    uses: ./.github/workflows/reusable-job.yml
    secrets: inherit
    with:
      name: Python CUDA image
      recipe: image-cuda
