on:
  workflow_call:
    inputs:
      name: 
        required: true
        type: string
      recipe:
        required: true
        type: string

jobs:
  create-job:
    runs-on: ubuntu-latest
    steps:
      - uses: aiplatforma/action-jobledger@v0
        with:
          name: ${{ inputs.name }}
          type: just
          metadata: |
            {
              "recipe": "${{ inputs.recipe }}",
              "repository": "aiplatforma.github.com:${{ github.repository }}",
              "tag": "main"
            }
          api-endpoint: ${{ secrets.JOBLEDGER_API_ENDPOINT }}
          api-token: ${{ secrets.JOBLEDGER_API_TOKEN }}
