on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
      image:
        required: true
        type: string
      tag:
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_REPOSITORY: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: tags
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}
          tags: |
            type=raw,value=${{ inputs.tag }}
      - name: Image metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          labels: |
            rs.gov.ite.aiplatforma.${{ inputs.image }}.version=${{ inputs.tag }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: src/${{ inputs.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.tags.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}